steps:
  - command: |
      echo "+++ :hammer: Building" && \
      echo 1 | ./build.sh && \
      echo "--- Compressing build directory :compression:" && \
      tar -pczf build.tar.gz build/
    artifact_paths: "build.tar.gz"
    label: ":darwin: Build"
    agents:
      role: "macos-builder"
    timeout: 60

  - command: |
        echo "+++ :hammer: Building" && \
        echo 1 | ./build.sh && \
        echo "--- Compressing build directory :compression:" && \
        tar -pczf build.tar.gz build/
    artifact_paths: "build.tar.gz"
    label: ":ubuntu: 16.04 Build"
    agents:
      role: "automation-builder-fleet"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:ubuntu"
        workdir: /data/job
    timeout: 60
    
  - command: |
        echo "+++ :hammer: Building" && \
        echo 1 | ./build.sh && \
        echo "--- Compressing build directory :compression:" && \
        tar -pczf build.tar.gz build/
    artifact_paths: "build.tar.gz"
    label: ":ubuntu: 18.04 Build"
    agents:
      role: "automation-builder-fleet"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:ubuntu18"
        workdir: /data/job
    timeout: 60

  - command: |
        echo "+++ :hammer: Building" && \
        echo 1 | ./build.sh && \
        echo "--- Compressing build directory :compression:" && \
        tar -pczf build.tar.gz build/
    artifact_paths: "build.tar.gz"
    label: ":fedora: Build"
    agents:
      role: "automation-builder-fleet"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:fedora"
        workdir: /data/job
    timeout: 60

  - command: |
        echo "+++ :hammer: Building" && \
        echo 1 | ./build.sh && \
        echo "--- Compressing build directory :compression:" && \
        tar -pczf build.tar.gz build/
    artifact_paths: "build.tar.gz"
    label: ":centos: Build"
    agents:
      role: "automation-builder-fleet"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:centos"
        workdir: /data/job
    timeout: 60
  
  - command: |
        echo "+++ :hammer: Building" && \
        echo 1 | ./build.sh && \
        echo "--- Compressing build directory :compression:" && \
        tar -pczf build.tar.gz build/
    artifact_paths: "build.tar.gz"
    label: ":aws: Build"
    agents:
      role: "automation-builder-fleet"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:amazonlinux"
        workdir: /data/job
    timeout: 60

  - wait

  - command: |
      echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":darwin: Build" && \
        tar -zxf build.tar.gz && \
        echo "+++ :microscope: Running tests" && \
        ./build/unit_test
    # artifact_paths: "build.tar.gz"
    label: ":darwin: Build"
    agents:
      role: "macos-builder"
    timeout: 60

  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":ubuntu: 16.04 Build" && \
        tar -zxf build.tar.gz && \
        echo "+++ :microscope: Running tests" && \
        ./build/unit_test
    # artifact_paths: "build.tar.gz"
    label: ":ubuntu: 16.04 Build"
    agents:
      role: "automation-builder-fleet"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:ubuntu"
        workdir: /data/job
    timeout: 60
    
  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":ubuntu: 18.04 Build" && \
        tar -zxf build.tar.gz && \
        echo "+++ :microscope: Running tests" && \
        ./build/unit_test
    # artifact_paths: "build.tar.gz"
    label: ":ubuntu: 18.04 Build"
    agents:
      role: "automation-builder-fleet"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:ubuntu18"
        workdir: /data/job
    timeout: 60

  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":fedora: Build" && \
        tar -zxf build.tar.gz && \
        echo "+++ :microscope: Running tests" && \
        ./build/unit_test
    # artifact_paths: "build.tar.gz"
    label: ":fedora: Build"
    agents:
      role: "automation-builder-fleet"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:fedora"
        workdir: /data/job
    timeout: 60

  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":centos: Build" && \
        tar -zxf build.tar.gz && \
        echo "+++ :microscope: Running tests" && \
        ./build/unit_test
    # artifact_paths: "build.tar.gz"
    label: ":centos: Build"
    agents:
      role: "automation-builder-fleet"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:centos"
        workdir: /data/job
    timeout: 60
  
  - command: |
        echo "--- :arrow_down: Downloading build directory" && \
        buildkite-agent artifact download "build.tar.gz" . --step ":aws: Build" && \
        tar -zxf build.tar.gz && \
        echo "+++ :microscope: Running tests" && \
        ./build/unit_test
    # artifact_paths: "build.tar.gz"
    label: ":aws: Build"
    agents:
      role: "automation-builder-fleet"
    plugins:
      docker#v1.4.0:
        image: "eosio/ci:amazonlinux"
        workdir: /data/job
    timeout: 60

    # - wait

  # - command: |
  #       echo "--- :arrow_down: Downloading build directory" && \
  #       buildkite-agent artifact download "build.tar.gz" . --step "":ubuntu: 16.04 Build" && \
  #       tar -zxf build.tar.gz && \
  #       echo "+++ :microscope: Starting package build" && \
  #       cd /data/job/build/packages && bash generate_package.sh deb
  #   label: ":ubuntu: 16.04 Package builder"
  #   agents:
  #     role: "automation-builder-fleet"
  #   artifact_paths:
  #     - "build/packages/*.deb"
  #   plugins:
  #     docker#v1.4.0:
  #       image: "eosio/ci:ubuntu"
  #       workdir: /data/job
  #   timeout: 60
